### PR TITLE
Camel case file names to snake case

### LINKED ISSUE #2: Commonize file names
Some files' name are snake cased, some are camel cased.
Please commonize them.(I like snake case)

ex.
date_time_generator.js
forLoops.js

### LINKED ISSUE #7: Fix camel-cased file name
There is still camel-cased file like `colourChanger.js`.
Please fix it 😄

### PR DESCRIPTION
**Pull request by kristinejosami**
I renamed files to snake case

### CODE REVIEW

**Comment by naokidney** [comment]
Can you set `Linked issues` on the right menu on this page?

**Comment by naokidney** [comment]
The word `colour` used in file names is typo??

**Comment by kristinejosami** [comment]
> The word `colour` used in file names is typo??

No, it's not a typo. It's British spelling. Can't I use British spelling?

**Review by naokidney — APPROVED** [review]
LGTM

**Pull request merged**
